'use client';
import { useEffect, useState } from 'react';
import type { ContentKey, ContentRecord } from '../../../lib/cms/types';
import { defaultHomepage, defaultServices, defaultTeam, defaultFaq, defaultContact } from '../../../lib/site-defaults';
import { api, RequestError, useUnsaved } from './api';
import { ImageField } from './media-library';
type Item = Record<string, string | null>;
type FormValue = Record<string, string | Item[]>;
const defaults = { homepage: { hero_image: '', hero_alt: '', ...defaultHomepage }, services: { items: defaultServices.map(item => ({ image: null, image_alt: '', ...item })) }, team: { items: defaultTeam }, faq: { items: defaultFaq }, contact: defaultContact };
const newItems: Partial<Record<ContentKey, Item>> = { services: { title: '', copy: '', image: null, image_alt: '' }, team: { name: '', role: '', bio: '', image: null }, faq: { question: '', answer: '' } };
const labels: Record<string, string> = { heading: 'Heading', introduction: 'Introduction', email: 'Email address', location: 'Location', title: 'Title', copy: 'Description', name: 'Name', role: 'Role', bio: 'Biography', question: 'Question', answer: 'Answer', label: 'Link label', url: 'Link URL', hero_alt: 'Hero image description', image_alt: 'Image description' };
function TextField({ name, value, change }: { name: string; value: string; change: (value: string) => void }) {
 const multiline = ['introduction', 'copy', 'bio', 'answer'].includes(name);
 return <label>{labels[name] || name}{multiline ? <textarea value={value} onChange={event => change(event.target.value)} /> : <input type={name === 'email' ? 'email' : name === 'url' ? 'url' : 'text'} value={value} onChange={event => change(event.target.value)} />}</label>;
}
function ItemEditor({ item, index, total, update, remove, move }: { item: Item; index: number; total: number; update: (item: Item) => void; remove: () => void; move: (direction: number) => void }) {
 return <div className="panel content-group"><div className="content-item-heading"><h3>{item.title || item.name || item.question || item.label || `Item ${index + 1}`}</h3><div className="studio-actions"><button className="button" disabled={index === 0} aria-label={`Move item ${index + 1} up`} onClick={() => move(-1)}>Up</button><button className="button" disabled={index === total - 1} aria-label={`Move item ${index + 1} down`} onClick={() => move(1)}>Down</button><button className="button danger" onClick={remove}>Remove</button></div></div>{Object.entries(item).map(([name, text]) => name === 'image' ? <div key={name}><h3>Image</h3><ImageField url={text || ''} alt={item.image_alt || item.name || ''} onChange={(url, alt) => update({ ...item, image: url || null, ...('image_alt' in item ? { image_alt: alt } : {}) })} /></div> : <TextField key={name} name={name} value={text || ''} change={text => update({ ...item, [name]: text })} />)}</div>;
}
function ContentFields({ value, section, change }: { value: FormValue; section: ContentKey; change: (value: FormValue) => void }) {
 return <>{Object.entries(value).map(([field, content]) => {
  if (field === 'hero_image') return <div key={field}><h3>Hero image</h3><ImageField url={String(content || '')} alt={String(value.hero_alt || '')} onChange={(url, alt) => change({ ...value, hero_image: url, hero_alt: alt })} /></div>;
  if (typeof content === 'string') return <TextField key={field} name={field} value={content} change={text => change({ ...value, [field]: text })} />;
  return <div key={field}>{content.map((item, index) => <ItemEditor key={index} item={item} index={index} total={content.length} update={next => change({ ...value, [field]: content.map((current, position) => position === index ? next : current) })} remove={() => { if (window.confirm('Remove this item? Save your changes to update the website.')) change({ ...value, [field]: content.filter((_, position) => position !== index) }); }} move={direction => { const reordered = [...content]; [reordered[index], reordered[index + direction]] = [reordered[index + direction], reordered[index]]; change({ ...value, [field]: reordered }); }} />)}<button className="button" onClick={() => change({ ...value, [field]: [...content, field === 'social_links' ? { label: '', url: '' } : { ...newItems[section] }] })}>Add {field === 'social_links' ? 'social link' : 'item'}</button></div>;
 })}</>;
}
export default function ContentEditor({ section, onDirty }: { section: ContentKey; onDirty: (dirty: boolean) => void }) {
 const [value, setValue] = useState<FormValue | null>(null); const [version, setVersion] = useState(0); const [dirty, setDirty] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [note, setNote] = useState(''); const [attempt, setAttempt] = useState(0); useUnsaved(dirty);
 useEffect(() => { const controller = new AbortController(); api<ContentRecord>(`/api/admin/content/${section}`, { signal: controller.signal }).then(record => { const loaded = (record.value || defaults[section]) as unknown as FormValue; if (section === 'homepage') { loaded.hero_image ??= ''; loaded.hero_alt ??= ''; } if (section === 'services' && Array.isArray(loaded.items)) loaded.items = loaded.items.map(item => ({ image: null, image_alt: '', ...item })); setValue(loaded); setVersion(record.version); setDirty(false); onDirty(false); setError(''); }).catch(issue => { if (issue.name !== 'AbortError') setError(issue.message); }); return () => controller.abort(); }, [section, attempt, onDirty]);
 function change(next: FormValue) { setValue(next); setDirty(true); onDirty(true); setNote(''); }
 async function save() { if (!value) return; setBusy(true); setError(''); try { const saved = await api<ContentRecord>(`/api/admin/content/${section}`, { method: 'PUT', body: JSON.stringify({ value, version }) }); setVersion(saved.version); setValue(saved.value as unknown as FormValue); setDirty(false); onDirty(false); setNote('Website content saved.'); } catch (issue) { setError(issue instanceof RequestError && issue.status === 409 ? 'This section changed in another session. Copy your changes before you reload.' : (issue as Error).message); } finally { setBusy(false); } }
 return <section className="panel"><h2>{section === 'faq' ? 'Frequently asked questions' : section.charAt(0).toUpperCase() + section.slice(1)}</h2><p className="muted">Saved changes appear on the website.</p>{error && <p className="notice error" role="alert">{error} <button className="link-button" onClick={() => { if (!dirty || window.confirm('Discard your changes and load the saved section?')) setAttempt(current => current + 1); }}>Reload</button></p>}{!value && !error && <p role="status">Loading content…</p>}{value && <><fieldset disabled={busy} style={{ border: 0, padding: 0, margin: 0, minWidth: 0 }}><ContentFields value={value} section={section} change={change} /></fieldset><div className="save-bar"><p role="status">{note || (dirty ? 'Unsaved changes' : 'No unsaved changes')}</p><button className="button primary" onClick={save} disabled={busy || !dirty}>{busy ? 'Saving…' : 'Save website content'}</button></div></>}</section>;
}
