'use client';
import { useRef } from 'react';
import type { PostInput, PostStatus } from '../../../lib/cms/types';
import { ImageField } from './media-library';
type ChangePost = <K extends keyof PostInput>(key: K, value: PostInput[K]) => void;
function StoryField({ value, change }: { value: string; change: (value: string) => void }) {
 const field = useRef<HTMLTextAreaElement>(null);
 function insert(text: string) { const input = field.current; if (!input) return; const start = input.selectionStart; const end = input.selectionEnd; change(value.slice(0, start) + text + value.slice(end)); requestAnimationFrame(() => { input.focus(); input.setSelectionRange(start + text.length, start + text.length); }); }
 return <div><label htmlFor="story-body">Story</label><div className="editor-toolbar" role="toolbar" aria-label="Story structure"><button type="button" onClick={() => insert('\n\nSection title\n\n')}>Add section</button><button type="button" onClick={() => insert('\n\n• First point\n• Second point\n\n')}>Add list</button><button type="button" onClick={() => insert('\n\n“Your quotation”\n\n')}>Add quote</button><button type="button" onClick={() => insert('\n\n')}>Paragraph break</button></div><textarea id="story-body" ref={field} required className="body-editor" value={value} maxLength={100000} onChange={event => change(event.target.value)} /><span className="field-hint">Use a blank line between paragraphs. Your story uses plain text.</span></div>;
}
export default function PostFields({ post, change, save, busy }: { post: PostInput; change: ChangePost; save: (status: PostStatus) => Promise<void>; busy: boolean }) {
 return <div className="editor-grid"><section><p className="editor-section-title">The story</p><label htmlFor="post-title">Post title</label><input id="post-title" className="post-title" required value={post.title} maxLength={180} onChange={event => change('title', event.target.value)} /><label htmlFor="post-excerpt">Short introduction</label><textarea id="post-excerpt" required value={post.excerpt} maxLength={400} onChange={event => change('excerpt', event.target.value)} /><span className="field-hint">Introduce the story for readers on the blog page.</span><StoryField value={post.body} change={value => change('body', value)} /></section><aside className="editor-side"><p className="editor-section-title">Publication</p><p><span className="badge">{post.status}</span></p><label htmlFor="post-category">Category</label><input id="post-category" required value={post.category} maxLength={80} onChange={event => change('category', event.target.value)} /><label htmlFor="post-author">Author</label><input id="post-author" required value={post.author} maxLength={120} onChange={event => change('author', event.target.value)} /><label htmlFor="post-slug">Page address</label><input id="post-slug" required value={post.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" onChange={event => change('slug', event.target.value)} /><span className="field-hint">Use lowercase words with hyphens.</span><label className="check"><input type="checkbox" checked={post.featured} onChange={event => change('featured', event.target.checked)} />Featured story</label><h3>Cover image</h3><ImageField url={post.cover_url} alt={post.cover_alt} onChange={(url, alt) => { change('cover_url', url); change('cover_alt', alt); }} /><label htmlFor="post-cover-alt">Image description</label><input id="post-cover-alt" required={!!post.cover_url} value={post.cover_alt} maxLength={240} onChange={event => change('cover_alt', event.target.value)} /><div className="studio-actions">{post.status !== 'published' && <button className="button primary" disabled={busy} onClick={() => save('published')}>Publish post</button>}{post.status === 'published' && <button className="button" disabled={busy} onClick={() => { if (window.confirm('Remove this post from the public blog?')) void save('draft'); }}>Unpublish</button>}{post.status !== 'archived' && <button className="button danger" disabled={busy} onClick={() => { if (window.confirm('Archive this post? It will leave the public blog.')) void save('archived'); }}>Archive</button>}{post.status === 'archived' && <button className="button" disabled={busy} onClick={() => save('draft')}>Restore as draft</button>}</div></aside></div>;
}
